### ISSUE TITLE
Where do I find the API Token?

### ISSUE THREAD

**Issue by Plainbroke** [sheyabernstein/MMM-pihole-stats#13]
Where do I find the API Token?
Do I get it from my Pi-Hole Admin or is there a website to get it.?

**Comment by sheyabernstein** [comment]
You can find it under API / Web interface in the Pi-Hole admin settings

**Comment by Plainbroke** [comment]
Thank you,  it took me a bit to find it, but it is working now.Any way to make it bigger? Jeff Burdick From: Sheya BernsteinSent: Sunday, August 15, 2021 5:07 PMTo: sheyabernstein/MMM-pihole-statsCc: Jeff; AuthorSubject: Re: [sheyabernstein/MMM-pihole-stats] Where do I find the API Token? (#13) You can find it under API / Web interface in the Pi-Hole admin settings—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
