### ISSUE TITLE
Pi-hole stats not updating

### ISSUE THREAD

**Issue by ProfessorShroom** [sheyabernstein/MMM-pihole-stats#18]
I see this has been an issue before but was fixed so not sure why it's come up again.
If I restart MM it will grab the latest info but will not update again
This was meant to be fixed in pr #14 but it's still doing it for me. I've checked the .js file and the fixed code is present and yet it isn't updating.

**Comment by sheyabernstein** [comment]
Please pull the latest commit

**Comment by ProfessorShroom** [comment]
I only started using it a week ago so there's no way I'm not on the latest

**Comment by sheyabernstein** [comment]
@charliehoward I just pushed a new commit :)

**Comment by ProfessorShroom** [comment]
That has fixed it thank you, although now it's flashing constantly, is there a config to disable that?

**Comment by sheyabernstein** [comment]
Check your updateInterval, it might be a short amount of time

**Comment by ProfessorShroom** [comment]
Ah yes it was thank you
