### ISSUE TITLE
only 1 domain blacklist is displayed

### ISSUE THREAD

**Issue by schlagucke** [sheyabernstein/MMM-pihole-stats#21]
Hello, 
I have the following error. 

Only 1 domain blacklist is displayed. Although several are used.

I use pi-hole 5.9 and the latest version of MagicMirror and MMM-pihole.

Thanks a lot. 

![087F0044-6635-4870-BA79-B35D5859CFB8](https://user-images.githubusercontent.com/96880539/153859513-e961aeb2-b452-43ad-90bc-fbaba2a74aa5.jpeg)
![3DB59E2A-EF60-49CF-A123-57569BCC9479](https://user-images.githubusercontent.com/96880539/153859531-58f8e23d-0889-4ba3-92f8-e73cb8b963ef.jpeg)
![1B28CEA5-7B26-495C-8282-01E9043CD711](https://user-images.githubusercontent.com/96880539/153859535-d46676ef-960d-4666-a2a4-bb47a330d0c1.jpeg)

**Comment by zinjacoder** [comment]
I guess I have a different question.  I just noticed my own instance (first time user of this plug-in) is showing the equivalent of "32 ads" and "61 DNS queries" where it should say "32,000 ads" and "61,000 DNS queries"  Have I overlooked something here?  

Thanks, sorry for the digression.

**Comment by sheyabernstein** [comment]
Hi @zinjacoder I've been unable to reproduce this issue. Can you please post your results from `<pihole>/admin/api.php`?

**Comment by barnosch** [comment]
Found the issue.
I reverted all _formatInt_ back to _formatFloat_, and everything is showed up in the mirror correctly, again.
Maybe you have to review that again.

**Comment by schlagucke** [comment]
Thank you for your work and effort.
It worked.

**Comment by sheyabernstein** [comment]
Hey @barnosch would you be able to submit a PR?
