### ISSUE TITLE
Not loading if enabled

### ISSUE THREAD

**Issue by barnosch** [sheyabernstein/MMM-pihole-stats#22]
Hi, i updated your module today after several years without having any issues.
Since the git pull, i just get a black screen, no error message or something.
If i disable the module with "disabled=true" everything is fine again, and the rest of the modules are loading.

I am not running the most actual MM² version, if this is important. (no idea how to figure out)

I installed the module for testing from scratch, and let the config untouched, except the apiURL.  Same error, just a black screen.

Tried to add the API Key with apiKey or apiToken in the config part... no chance.
Can you please give an advice?

**Comment by sheyabernstein** [comment]
Hi @barnosch please see [this link](https://docs.magicmirror.builders/getting-started/upgrade-guide.html) on how to upgrade MM

**Comment by barnosch** [comment]
did that and crashed everything!
I had to upgrade from Jessie to Stretch and reDo some stuff from MM in order to get it to work again.
Anyway, i have the mirror running again.

Now i have the problem that it only shows me to digits from what he is blocking.
For instance mirror says :
12 Ads blocked (56,1%)
20 DNS queries, 1 domains blacklisted

but the api says that:
domains_being_blocked | 1322355
dns_queries_today | 22603
ads_blocked_today | 12443
ads_percentage_today | 55.050213

%is right, the rest is cutted, i guess.
No idea what is wrong, do you have any idea?

_Edith. Same issue like the other open issue_

**Comment by sheyabernstein** [comment]
Hi @barnosch please see the `floatingPoints` config setting in the [README.md](https://github.com/sheyabernstein/MMM-pihole-stats/blob/master/README.md)

**Comment by barnosch** [comment]
Sorry to be annoying, but it makes no difference, if i set floatingPoints to 0, 2, or 8.
Still says "8 Ads blocked (50,4%)  instead of 8952
17 DNS queries, 1 domains blacklisted (should be 17540 DNS 1.322.586 Domains)
API is correct, seems to be he is cutting somewhere. Only the % value is correct.
