### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by BlackiSchwarz** [sheyabernstein/MMM-pihole-stats#24]

**Comment by BlackiSchwarz** [comment]
Hello,
I am new to GitHuB, so please forgive me if I still make mistakes. I know there is already a post on this topic, but it couldn't help me and is already closed.
I have piHole and this module set up on my Raspberry PI 4. However, no matter what I do, all I get is "Loading". Other modules work and I can also access the web interface of the PiHole and open "http://pi.hole/admin/api.php".

My configuration currently looks like this: 
module: "MMM-pihole-stats",
			position: "bottom_left", 
			config: {
				apiToken: "XXX",
				apiURL: "0.0.0.0/admin/api.php"
			}

I have also tried the apiURL with localhost, the IP address and the hostname.

Does anyone have an idea what could be wrong?

**Comment by sheyabernstein** [comment]
Hiya, have you obtained the API token from the PiHole web interface, and is the API url pointing to the PiHole's IP address?

You can also inspect element on MagicMirror to see the reason for any failing requests

**Comment by BlackiSchwarz** [comment]
Yes i copied the API from the PiHole web interface. The PiHole is installed on the same device as the MagicMirror. I tried it with the 192.168.X.X IP-Adress too, but it didn't work

How can i inspect the element on the MagicMirror?

**Comment by sheyabernstein** [comment]
Load the url in your browser > right click > inspect element > check the network tab to see all requests

**Comment by BlackiSchwarz** [comment]
MMM-pihole-stats.js does a request, but on Port 8080 and not on the PiHole-Port 80.

What am i supposed to find?

**Comment by sheyabernstein** [comment]
You can configure the port as needed. All configuration options are listed in the README

**Comment by BlackiSchwarz** [comment]
i didn't change a thing

But now its working

Thank you
