### ISSUE TITLE
Ad blocking data doesn't show

### ISSUE THREAD

**Issue by skruglov2023** [sheyabernstein/MMM-pihole-stats#26]
![image](https://user-images.githubusercontent.com/55259393/210120927-f58a81f0-4688-43d2-bbf1-e133dfd80ce9.png)
It loads clients/client data just fine, but none of the overall data shows up.
![image](https://user-images.githubusercontent.com/55259393/210120938-4d914e80-1113-46f2-a859-40f76642606d.png)
The data exists, and I can reach it on the same url as the one put in the config.
![image](https://user-images.githubusercontent.com/55259393/210120965-09030a85-a612-45f6-989d-c98ea30ebdd2.png)

**Comment by sheyabernstein** [comment]
Hi @skruglov2023 are you getting any console errors?

**Comment by skruglov2023** [comment]
No, I'm not getting any console errors, or any errors at all rather

**Comment by skruglov2023** [comment]
Ignore that, I checked the current PR, #25, and the fix on line 20 there makes the ads-blocked info show up just fine. 
Line 22 there is fine as-is, without the PR fix.

**Comment by sheyabernstein** [comment]
@skruglov2023 this issue has now been resolved by merging PR #27
