### ISSUE TITLE
"Ads blocked today" showing 0% - DNS and blacklist showing 0

### ISSUE THREAD

**Issue by petedin** [sheyabernstein/MMM-pihole-stats#28]
A few months ago the displayed data no longer shows total number of "ads blocked today" and is defaulting to 0 ads and 0% and the DNS queries and blacklisted stats both show 0.

The stats for individual clients are updating properly.

I have changed nothing in MM. It's been running for almost a year non-stop with no configuration changes.
I'm quite sure that this was caused by a PiHole update at some point, but is this a known issue? I been searching for days before deciding to post here.

Not sure of the MMM-pihole-stats version currently running, but it was installed on 4/22/2022 and I've made no edits other than for the IP and API.

I removed the install and re-cloned the repository, but after config of IP and API, getting same results.

_Here is screenshot of what is now displayed:_

![PiHole](https://github.com/sheyabernstein/MMM-pihole-stats/assets/103080821/8d100e47-a001-43bb-bcf8-0ce061142f96)

I really LOVE this plugin and hope to get it working 100% again.
Thank you for all your hard work on this project and I truly appreciate it!

**Comment by sheyabernstein** [comment]
Hi, this might be [CORS related](https://www.reddit.com/r/raspberry_pi/comments/qskua3/failed_cors_when_trying_to_fetch_api_results_from/). A fix for this was applied in #9

Are any related errors appearing in the dev console?

**Comment by KristjanESPERANTO** [comment]
This problem doesn't occur with the current version of the module on my system. Since @petedin didn't react, I think this issue can be closed.
