### ISSUE TITLE
screen doesn't

### ISSUE THREAD

**Issue by rickde92** [sheyabernstein/MMM-pihole-stats#30]
When I try to integrate Pi Hole the screen doesn't start and the following message appears in the log.

`0|MagicMirror  | [26.02.2024 08:56.24.927] [ERROR] (node:3093) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-fetch'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/admin/MagicMirror/modules/MMM-pihole-stats/node_helper.js
0|MagicMirror  | - /home/admin/MagicMirror/js/app.js
0|MagicMirror  | - /home/admin/MagicMirror/js/electron.js
0|MagicMirror  | - /home/admin/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at node:internal/modules/cjs/loader:1084:15
0|MagicMirror  |     at Function.<anonymous> (node:electron/js2c/browser_init:2:116118)
0|MagicMirror  |     at Module._resolveFilename (/home/admin/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at node:internal/modules/cjs/loader:929:27
0|MagicMirror  |     at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMirror  |     at Object.<anonymous> (/home/admin/MagicMirror/modules/MMM-pihole-stats/node_helper.js:2:15)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|MagicMirror  |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMirror  |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMirror  |     at node:internal/modules/cjs/loader:967:12
0|MagicMirror  |     at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMirror  |     at loadModule (/home/admin/MagicMirror/js/app.js:181:19)
0|MagicMirror  | (Use `electron --trace-warnings ...` to show where the warning was created)
0|MagicMirror  | [26.02.2024 08:56.24.928] [ERROR] (node:3093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`

**Comment by sheyabernstein** [comment]
Hi, please update to the latest version and run `npm install` within the module directory.

`node-fetch` was removed from MagicMirror so the module now uses `request`.

**Comment by rickde92** [comment]
I Delete the folder MMM-Pihole-stats and git the new version. 

my config:
`		{//MMM-pihole-stats- top_left
			module: 'MMM-pihole-stats',
		    	position: "top_left",
				header: "MMM-pihole-stats",
				config: {
					apiURL: "http://10.0.16.100/admin/api.php",
					apiToken: "b6a4991bc3c215073550b538c146ac340d486befc0cdfd77aa4a9562491b3c96"
				}
	  	},
`


log:
`/home/admin/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir |     at node:internal/modules/cjs/loader:929:27
0|MagicMir |     at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMir |     at Object.<anonymous> (/home/admin/MagicMirror/modules/MMM-piho                                                                             le-stats/node_helper.js:2:17)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|MagicMir |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMir |     at node:internal/modules/cjs/loader:967:12
0|MagicMir |     at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMir |     at loadModule (/home/admin/MagicMirror/js/app.js:181:19)
0|MagicMir | (Use `electron --trace-warnings ...` to show where the warning was                                                                              created)
0|MagicMir | [27.02.2024 08:10.06.437] [ERROR] (node:2982) UnhandledPromiseRejec                                                                             tionWarning: Unhandled promise rejection. This error originated either by throwi                                                                             ng inside of an async function without a catch block, or by rejecting a promise                                                                              which was not handled with .catch(). To terminate the node process on unhandled                                                                              promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https:/                                                                             /nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`
