### ISSUE TITLE
Module is stuck on loading

### ISSUE THREAD

**Issue by BerkSmash1984** [sheyabernstein/MMM-pihole-stats#35]
Just installed this module fresh, but it is stuck on loading:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/776dfd4f-5ef8-4af0-9d79-8485a5ef97b3)

Here is my config:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/77b6ba0c-15db-4a41-b0cd-7e7f9ad205db)

Here is what I am seeing in the logs:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/6a5d20ff-22e4-431c-8ddd-e9641bd2db17)

Any thoughts?

**Comment by sheyabernstein** [comment]
Hi @BerkSmash1984, can you see a request to your Pi-Hole instance in the network logs? If so, what does the response look like?

The Pi-Hole API returns responses as `application/json`, perhaps it is not loading. Also, the `apiURL` should contain the port if it is not the default `80` for http.

**Comment by BerkSmash1984** [comment]
The Pi-hole is actually running on the same device as the MagicMirror (my RPI 4B) and is using standard port 80 for http traffic. 

Dev mode on the browser is not showing anything revealing. Which network logs did you want me to check, specifically? Pi-hole itself is not showing anything, but again, it is talking to itself since it is all on the same device.

**Comment by sheyabernstein** [comment]
Can you see the HTTP response from the pihole requests in the network console?

#37 will not throw exceptions on HTTP error in this module, so it should not continue to interrupt MagicMirror's startup.

**Comment by BerkSmash1984** [comment]
Appreciate your responses. I'll check in the morning via the network dev console and get back to you, but it doesn't prevent my MagicMirror from loading, it's just the pihole stats module never loads.

**Comment by BerkSmash1984** [comment]
I just checked the Network tab in the Dev console but not seeing any requests related to the pi-hole stats module:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/c7e6feb2-f08d-4447-b03d-ed23bdb3fd86)

**Comment by robklingler** [comment]
I am seeing the same thing (i.e. stuck on "Loading.")

My Magic Mirror logs shows " [ERROR] MMM-pihole-stats: TypeError: fetch failed"

**Comment by sheyabernstein** [comment]
Hi, are you running the latest version of this module and magicmirror?

**Comment by AWSW-de** [comment]
Hi,
just installed a new MM and this module today and can confirm this loading stuck issue.

- Newest versions of MM, Pi-Hole and this module installed.
- http://pi.hole/admin/api.php shows the current data 
- Tried with and without api Token
- No password set for the pi hole web page 

Thanks for a fix in advance =)

**Comment by robklingler** [comment]
I think I found the issue/solution.

First, background:
- Latest MM (via khassell's docker container setup - https://khassel.gitlab.io/magicmirror)
- Latest Pihole
- Previously No API Token or Password

I first tried creating an API token, which also required establishing a password.  Did both of these, no change.

I then noted that the apiURL wasn't working, as it wasn't picking up the correct port.  (I previously had a "port: " configuration in my MM config file, but now see that option is not listed in the current module configuration options.)

I added the port to by apiURL (http://192.168.1.1:808/admin/api.php) and rebooted MM. 

Everything now is back to working.  And works with and without API and/or password.

**Comment by sheyabernstein** [comment]
@robklingler the port config was indeed removed recently. Will add it to the readme too.

**Comment by AWSW-de** [comment]
Hi,
the port was not the solution for my setup although I changed it too.

I got it working meanwhile by changing the apiURL to the IP-address instead of the pi.hole url:

apiURL: "http://192.168.1.15/admin/api.php"

Now it shows the data.

Thanks and kind regards =)

**Comment by robklingler** [comment]
(And thank you for removing the dependency on fetch, which through an error every time I updated the MM container.  I knew how to fix it, but it required manual steps, and ultimately caused me not to regularly update the MM container.)

**Comment by sheyabernstein** [comment]
The README has been updated to highlight the removal of the `port` config option in #38 . Thanks all for raising this issue.

**Comment by BerkSmash1984** [comment]
Maybe update the code snippet showing the port in the apiURL config so it
is clear. Right now the code doesn’t show absolute URL; it doesn’t have the
port.


Respectfully,

Jordan Berkebile

**Comment by BerkSmash1984** [comment]
@sheyabernstein This still is not working for me, even with absolute URL

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/1de46370-a85c-4e05-9045-eee6ae8d3281)

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/3b104d54-1d2a-439b-b5e7-b680005af24a)

Yes, I am using latest MM and latest module (just downloaded it this AM to retest.

In the logs, it is still showing this:
![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/9fc780f2-634b-4bba-ba80-6d0fd469f013)

**Comment by sheyabernstein** [comment]
@BerkSmash1984 please verify that you can ping the Pi-hole URL from the MagicMirror devtools.

**Comment by BerkSmash1984** [comment]
@sheyabernstein the MM and Pihole are running on the same device, a Raspberry Pi 4.

**Comment by sheyabernstein** [comment]
@BerkSmash1984 the `apiURL` in your config is not pointing to the Pi-hole API. Please check your config.

**Comment by BerkSmash1984** [comment]
@sheyabernstein  it 100% is pointing to the correct URL. It doesn't matter if I use IP or actual URL, with port 80 specified, or without

Directly from my RPI4:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/e51ea32e-c6e8-46d3-8c07-e8d6424e950a)

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/c696920c-33eb-47ca-a3f4-8556e3cf077b)


MM config:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/5b6434ff-83d7-4c0f-bf2e-36c60bcc5ee0)

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/81c91c6a-3b0d-4c99-a5c7-63d1b1956784)

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/9995e527-ae64-4e3b-9822-475a76d784b4)


^^^ I tried all possible configs...

Still stuck on loading

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/195a6f32-c666-4a6b-b25e-95c06ccbc632)

**Comment by sheyabernstein** [comment]
The url in your screenshots point to the admin/dashboard page at `/admin/index.php` and the login page at `/admin/login.php`. Your url should end with `admin/api.php` for the API as defined in the readme.

This is also why you are seeing `Expected JSON but received text/html` in your errors. The url was pointing to a path that returns HTML.

Please open a new issue if you continue to have any trouble.

**Comment by BerkSmash1984** [comment]
Ah let me take another look I must have missed that somehow, and will do. Thanks!

**Comment by BerkSmash1984** [comment]
@sheyabernstein appreciate you handing in there with me! That was in fact the issue and the module is now working:

![image](https://github.com/sheyabernstein/MMM-pihole-stats/assets/104693081/bae2f7b1-6346-4530-a31d-b031a122d5ee)


Thanks again!
