### ISSUE TITLE
Module locking up Raspberry Pi / Tied into high Electron CPU use.

### ISSUE THREAD

**Issue by teknohe** [sheyabernstein/MMM-pihole-stats#6]
Hello, 

After troubleshooting my Raspberry Pi 3 (Model B / ARMv8) for several days I discovered this module was the cause of my MagicMirror / Raspberry Pi locking up and possibly overheating due to high CPU use.  My CPU was pushing past 100% whenever Piholestats updated.  

Even decreasing the frequency of the updates didn't correct this.  I'd find my system was stable at most for 3-4hours before locking up.

Before I discovered this module was the cause, I tried multiple versions of MagicMirror / Raspbian / Electron without success.  Removing this module completely stopped lockups. 

Hope it helps with a fix,

**Comment by spidermedic** [comment]
Same problem here. I reinstalled my MM and added one module at a time. pihole-stats is clearly causing an overheat. My MM runs at 37 / 38 without it.
