### ISSUE TITLE
 MMM-pihole was causing major bugs/ freezes 

### ISSUE THREAD

**Issue by nakulbende** [sheyabernstein/MMM-pihole-stats#7]
Hello all,

This is just a PSA - I believe the module MMM-Pihole was causing my mirror to crash badly, mostly causing it to loose connection, freeze every 2-3 hours. Here is the chronological scenario:

- Updated MM
-  Tested with many many configurations of modules. I spent almost a month debugging it - and ran all permutations and combinations of why the mirror is freezing. The logs only showed internet disconnect
-  I looked at the logs, which were not really helpful. He suggested to move the installation form a SD card to USB. I did this, and in addition added active cooling fan to the pi, so we can strike off cooling issues. My pi was freezing/ acting up even when the temps never went above 40
-  MMM-Pihole - only with just that module running caused bugs. As soon as I disabled it, running all the modules cased no bugs. Compare 1-2 hour of stability vs. running for last month without errors
-  Freezes are obvious, but I even got partial mirror displayed. Weird, so leaving a snapshot here (look at the calendar and time module):

![image](https://user-images.githubusercontent.com/8712050/85806753-f9bbf200-b71d-11ea-879e-fd15518aa596.png)

So, if you are using the module, and are having issues - try taking it off, hope it solves your issue.

**Comment by Plainbroke** [comment]
Having Same Problem, If you get an answer please put it in the comments here...

Every time I try to use MMM-pihole, I am getting the same issue.  I am thinking it is a configuration error and tried 20+ ways of configuring the module with absolutely no joy.  Does not work on my Pi4 2gb either.   I have run out of ideas why it won't work.

**Comment by nakulbende** [comment]
I dont think anything can be done on the user's side. I believe there are
some issues with the module - your config might be OK.



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett

**Comment by sheyabernstein** [comment]
This is been fixed in the latest commit. Please check out item 3 in the readme

**Comment by nakulbende** [comment]
@sheyabernstein !! thanks

So it should look like this: 

```
$HTTP["url"] =~ "^/admin/api.php" {
    setenv.add-environment = (
  		"SERVER_NAME" => "192.168.1.115"
	)
}
```

if 192.168.1.115 is my PiHole IP? Or should this be the IP of MagicMirror?

**Comment by sheyabernstein** [comment]
@nakulbende it should be the IP of the pihole
